#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.gjf] "
    echo ""
    echo "如果未提供文件名，则对当前目录下的所有*.gjf文件执行命令"
    echo ""
    echo "生成 icss 文件并计算"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# 如果传入了文件名，则使用该文件，否则使用所有 .log 文件
if [[ -n "$1" ]]; then
    file_pattern="$1"
else
    file_pattern="*_icss.gjf"
fi

# 执行转换和移动的函数
process_file() {
    local ito=$1
    echo "Converting .gjf"
    Multiwfn ${ito} << EOF > /dev/null 2>&1
25
3
-10
12
1
n
exit
EOF
    g16s *001.gjf
    check_error "运行 Multiwfn ${ito}"
}


wait

found=false


for dir in $(find . -type d -name "*_icss"); do
    found=true
    echo '进入每个文件夹生成 icss 文件'
    # 进入每个找到的文件夹
    cd "$dir"
    # 检查info.txt文件是否存在
    if [ -f *_icss.gjf ]; then
        # 如果存在，执行cat命令
        process_file *_icss.gjf
        echo "------" # 用于分隔不同文件夹的输出
    else
        echo "gjf not found in $dir"
    fi
    # 返回上一级目录
    cd ..
done


#find . -type d -name "*_icss" | while read dir; do
#    found=true
#    echo '进入每个文件夹生成 icss 文件'
#    # 进入每个找到的文件夹
#    cd "$dir"
#    # 检查info.txt文件是否存在
#    if [ -f *_icss.gjf ]; then
#        # 如果存在，执行cat命令
#        process_file *_icss.gjf
#        echo "------" # 用于分隔不同文件夹的输出
#    else
#        echo "gjf not found in $dir"
#    fi
#    # 返回上一级目录
#    cd ..
#done


if [ "$found" = false ]; then
    echo "在当前文件夹下生成 icss 文件"
    process_file $file_pattern
fi

exit 0

