#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法: $(basename "$0") [filename.chk]  计算重组能对振动的分解，及振动分辨光谱"
    echo ""
    echo "如果提供了文件名，则替换命令中的*.chk为指定文件"
    echo "如果未提供文件名，则对当前目录下的所有*.chk文件执行命令"
    echo ""
    echo "需要 ./ 和 ./tdopt 做振动分析"
}

# 如果传入了文件模式，则使用该模式，否则使用所有 .chk 文件
file_pattern=$(ls *.chk)
if [[ -n "$1" ]]; then
    file_pattern="$1"
fi

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

mkdir -p reorg_gau

for inf in $file_pattern;do
    cp ./$inf ./reorg_gau
    cp ./tdopt/${inf//.chk/_tdopt.chk} ./reorg_gau
done

wait

cd reorg_gau

for inf in $file_pattern;do
output_file="${inf//.chk/_reorg_gau.gjf}"
    
    # 写入内容到输出文件
    cat << EOF > "$output_file"
%mem=80GB
%nproc=32
%oldchk=$inf
#p geom=allcheck freq(readfc,fcht,readfcht)

initial=source=chk final=source=chk spectroscopy=onephotonemission Temperature

${inf//.chk/_tdopt.chk}
$inf
EOF

    echo "Written to $output_file"
done

g16s *_reorg_gau.gjf

echo "已全部提交任务"
