#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.log] "
    echo ""
    echo "如果提供了文件名，则替换命令中的*.log为指定文件"
    echo "如果未提供文件名，则对当前目录下的所有*.log文件执行命令"
    echo ""
    echo "当前目录下优化好的基态结构"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# 如果传入了文件名，则使用该文件，否则使用所有 .log 文件
if [[ -n "$1" ]]; then
    file_pattern="$1"
else
    file_pattern="*.log"
fi

# 生成 ICSS 计算文件
gen_gif() {
    local input=$1
    qcinp.py -k 'pbe1pbe def2svp nmr=csgt iop(10/93=1)' -A _AICD $input
    mkdir -p "AICD"
    sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' ${input//.log/_AICD.gjf}
    echo "" >> ${input//.log/_AICD.gjf}
    echo "${input//.log/_aicd.txt}" >> ${input//.log/_AICD.gjf}
    echo "" >> ${input//.log/_AICD.gjf}
    echo "" >> ${input//.log/_AICD.gjf}
    mv ${input//.log/_AICD.gjf} AICD
}



# 处理文件
if [[ "$file_pattern" == "*.log" ]]; then
    for file in $file_pattern; do
        gen_gif "$file"
    done
else
    gen_gif "$file_pattern"
fi

wait

cd AICD
g16s *_AICD.gjf

exit 0

#found=False

#find . -type d -name "*_icss" | while read dir; do
#    found=True
#    # 进入每个找到的文件夹
#    cd "$dir"
#    # 检查info.txt文件是否存在
#    if [ -f *_icss.gjf ]; then
#        # 如果存在，执行cat命令
#        process_file *_icss.gjf
#        echo "------" # 用于分隔不同文件夹的输出
#    else
#        echo "gjf not found in $dir"
#    fi
#    # 返回上一级目录
#    cd ..
#done


#if [ "$found" = false ]; then
#    process_elements "$file_pattern"
#fi


