#!/bin/bash

# 显示帮助信息
show_help() {
    echo
    echo "用法: $(basename "$0") [pattern.log]"
    echo
    echo "如果提供了文件模式，则处理匹配的 .log 文件"
    echo "如果未提供文件模式，则处理当前目录下的所有 .log 文件"
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# 如果传入了文件模式，则使用该模式，否则使用所有 .log 文件
file_pattern="*.log"
if [[ -n "$1" ]]; then
    file_pattern="$1"
fi

# 计算是否正常结束
freq_num=0
for inf in $file_pattern; do
    if grep -q "freq" ${inf/.log/}.gjf ; then
        ((freq_num++))
    fi
done

# 计算正常结束的文件数量
finish_num=$(grep "Normal termination of Gaussian" $file_pattern | wc -l)

# 计算传入文件数量
file_num=$(ls -1 ${file_pattern} 2>/dev/null | wc -l)
echo "当前文件夹计算了 $file_num 文件"

# 检查 log 文件是否正常结束
echo "检查 log 文件是否正常结束"
if [[ $finish_num -ne $((file_num + freq_num)) ]]; then
    echo "计算未正常结束，条件：$finish_num ≠ $((file_num + freq_num)) "
    exit 0
fi

echo "已正常结束，开始计算激发态，条件：$finish_num ＝ $((file_num + freq_num)) "

# 创建目录，如果它们不存在
mkdir -p ./tdopt
mkdir -p ./tdvert

# 处理 .log 文件生成 .gjf 文件
qcinp.py -a 'td density=rhoci IOp(9/40=4)' -A '_tdopt' ${file_pattern}
qcinp.py -a 'td=triplet density=rhoci IOp(9/40=4)' -A '_tdopt_tri' ${file_pattern}
qcinp.py -r 'opt freq' -P soc -A '_tdvert' ${file_pattern}

# 移动生成的 .gjf 文件到各自的目录
mv *_tdvert.gjf ./tdvert
mv *_tdopt.gjf ./tdopt
mv *_tdopt_tri.gjf ./tdopt

# 等待所有后台进程完成
wait


