#!/bin/bash

# 定义帮助函数
show_help() {
    echo "Usage: $(basename "$0") num 共多少个 log 文件，一般为17个 也会有 18 个的情况 "
    echo "This script searches for directories named '*_icss' and performs operations based on the presence of a 'Normal termination of Gaussian' string in *.log files."
    echo ""
    echo "或者直接处理当前文件夹下 NICS 文件"
    echo ""
    echo "Options:"
    echo "  -h, --help     Show this help message and exit"
}

# 检查是否传入了帮助选项
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# 循环从1到17，每次增加1

num=${1:-17}

process_elements() {
    local counter=2
    while [ $counter -le $num ]
    do
        # 格式化数字为4位数，不足的前面补0
        formatted_counter=$(printf "%04d" $counter)
        # 构建元素并添加到列表
        element="NICS${formatted_counter}.gjf"
        # 显示元素
        g16s $element
        # 计数器增加
        ((counter++))
    done
}

found=false

for dir in $(find . -type d -name "*_icss"); do
#find . -type d -name "*_icss" | while read dir; do
    found=ture
    # 进入每个找到的文件夹
    cd "$dir"
    # 检查info.txt文件是否存在
    if grep -q "Normal termination of Gaussian" *.log; then
        # 如果存在，执行cat命令
        process_elements
        echo "执行文件生成" # 用于分隔不同文件夹的输出
    else
        echo "Normal termination not found, skipping operation..."
    fi
    # 返回上一级目录
    cd ..
done

# 如果没有找到任何icss的文件夹，则直接运行process_elements
if [ "$found" = false ]; then
    process_elements
fi


