#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法: $(basename "$0") [filename.out]"
    echo "查看 CCSD 计算的激发态能级。"
    echo "如果提供了文件名，则替换命令中的*.out为指定文件"
    echo "如果未提供文件名，则对当前目录下的所有*.out文件执行命令"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
        exit 1
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# 如果传入了文件名，则使用该文件，否则使用所有 .log 文件
file_pattern=$(ls *.out | grep -v '^slurm')
if [[ -n "$1" ]]; then
    file_pattern="$1"
fi

# 计算传入文件数量
file_num=$(ls -1 ${file_pattern} 2>/dev/null | wc -l)

# 如果没有文件，退出脚本
if [[ $file_num -eq 0 ]]; then
    echo "没有找到匹配的 .out 文件。"
    exit 1
fi

#rm slurm-*
#rm sub_*sbatch


excit() {
	local filename=$1
	echo $filename
	echo "=== SINGLETS Excited States ==="
    awk '/STEOM-CCSD results for excited SINGLETS/{flag=1; next}
         /STEOM-CCSD results for excited TRIPLETS/{flag=0}
         flag && /IROOT= *[0-1]+/{print}' "$filename"

    # 提取三重态(TRIPLETS)的IROOT信息
    echo -e "\n=== TRIPLETS Excited States ==="
    awk '/STEOM-CCSD results for excited TRIPLETS/{flag=1; next}
         /STEOM-CCSD SPIN-ORBIT COUPLING/{flag=0}  # 可以根据实际情况修改结束条件
         flag && /IROOT= *[0-3]+/{print}' "$filename"

    echo ""
    echo ""
}

for i in  $file_pattern;do
      excit $i
done
