#!/bin/env python
import numpy as np
import os
import re
import argparse

HRindexfile = "HuangRhys.dat"
Fccfile = "fcclasses.out"
parser = argparse.ArgumentParser(description="对于 fcclass3 计算得到的 HR index 数据进行处理，需要当前目录下的 HuangRhys.dat fcclasses.out")
args = parser.parse_args()


def ReadHRindex(HRindexfile):
    print(f"reading ReadHRindex:{HRindexfile}")
    HRindex = []
    slag = 0
    RH = open(HRindexfile, 'r', encoding='utf8')
    for line in RH:
        if 'Huang-Rhys' in line:
            slag = 1
            continue
        if slag == 1 and len(line.strip().split()) ==2:
            HRindex.append(line.strip().split()[-1])
    RH.close()
    return HRindex
if not os.path.isfile(HRindexfile):
    print(f"File {HRindexfile} does not exist.")
    pass
else:
    HRindex = np.array(ReadHRindex(HRindexfile)).astype(np.float32)

def Readfreq(Fccfile):
    print(f"reading Readfcc.out: {Fccfile}\n")

    # 更新后的正则表达式
    pattern = r'------------------------\s+FREQUENCIES \(cm-1\)\s+------------------------\s+((?:\s*\d+\s+[-+]?\d*\.\d+|\d+\s*)+)\s+------------------------'
    with open(Fccfile, 'r', encoding='utf8') as FR:
        content = FR.read()

    # 查找"VIBRATIONAL ANALYSIS ON STATE2"字符串
    state2_index = content.find("VIBRATIONAL ANALYSIS ON STATE2")

    # 如果找到指定字符串则继续匹配频率数据
    all_frequencies = []
    if state2_index != -1:
        content = content[state2_index:]  # 从"VIBRATIONAL ANALYSIS ON STATE2"开始截取内容
        matches = re.findall(pattern, content)

        for match in matches:
            frequencies = re.findall(r'^\s*\d+\s+([-+]?\d*\.\d+|\d+)', match, re.MULTILINE)
            all_frequencies.append(frequencies)

    return all_frequencies
if not os.path.isfile(Fccfile):
    print(f"File {Fccfile} does not exist.")
    pass
else:
    all_frequencies = np.array(Readfreq(Fccfile)).astype(np.float32)

# 计算重组能 (单位: cm⁻¹)
reorganization_energy = 1.239841E-1 * HRindex * all_frequencies[0]

with open('freq-hrindex-energy.txt', 'w') as f:
    f.write("Vibration frequency (cm-1)\t Huang-Rhys index\t Reorganization energy (meV)\n")  # 写入表头信息
    for freq, hr, energy in zip(all_frequencies[0], HRindex, reorganization_energy):
        f.write(f"{freq}\t{hr}\t{energy}\n")  # 保留4位小数

print("数据已写入到文件 'freq-hrindex-energy.txt' 中。")
