#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.fchk] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.fchk 文件使用"
    echo ""
    echo "生成 EPS Col 对面积微分分布"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.fchk"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_fchk() {
    local ito=$1
    echo "Converting $1"
    Multiwfn ${ito} << EOF > ${ito/.fchk/}-esp-area.txt 2>&1
12
0
9
all
-100,100
40
3
exit
EOF
}


# 处理文件 Area unit is in Angstrom^2


for i in $file_pattern ;do
    deal_fchk $i
    awk '/Area unit is in Angstrom/,/Sum:/' ${i/.fchk/}-esp-area.txt > ${i/.fchk/}-esp1.txt
    mv ${i/.fchk/}-esp1.txt ${i/.fchk/}-esp-area.txt 
done

wait

exit 0

