#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.log] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.log 文件使用"
    echo ""
    echo "生成多个激发态的 UV-Vis 光谱文件"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.log"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_log() {
    local ito=$1
    echo "Converting $1"
    Multiwfn ${ito} << EOF > /dev/null 2>&1
11
3
8
0.2
2
exit
EOF
}


# 处理文件


for i in $file_pattern ;do
    deal_log $i
    mv spectrum_curve.txt ${i/.log/}_spc.txt
    mv spectrum_line.txt ${i/.log/}_spl.txt
done

wait

exit 0

