#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.fchk] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.fchk 文件使用"
    echo ""
    echo "生成按照元素定义的 PDOS 投影的态密度图 (Column1: Energy Column 2: TDOS Column3-13: H C N O P Ca)"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.fchk"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_fchk() {
    local ito=$1
    echo "Converting $1"
    Multiwfn ${ito} << EOF > /dev/null 2>&1
10
7
3
-1
1
H
2
C
3
N
4
S
5
H
6
Ni
7
Mg
8
H
q
8
0
3
exit
EOF
}


# 处理文件


for i in $file_pattern ;do
    deal_fchk $i
    mv DOS_line.txt ${i/.fchk/}_DOS_line.txt
    mv DOS_curve.txt ${i/.fchk/}_DOS_curve.txt
done

wait

exit 0

