#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.fchk] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.fchk 文件使用"
    echo ""
    echo "生成自旋布居 .chg，以及自旋密度 .cub 文件，可配合 VMD 绘制"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.fchk"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_fchk() {
    local ito=$1
    local exn=$2
    echo "Converting .fchk"
    Multiwfn ${ito} << EOF > /dev/null 2>&1
18
1
${ito/.fchk/}.log
$exn
1
2
16
exit
EOF
}


# 处理文件


for i in $file_pattern ;do
    for n in {1..10};do
        deal_fchk $i $n
        mv Cele.cub ${i/.fchk/}_${n}_Cele.cub
        mv Chole.cub ${i/.fchk/}_${n}_Chole.cub
    done
done

wait

exit 0

