#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename_tdopt.fchk] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *_tdopt.fchk 文件使用"
    echo ""
    echo "生成第一激发态的 transition density, and transition electric/magnetic dipole moment density 等信息"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.fchk"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_fchk() {
    local ito=$1
    echo "Converting .fchk"
    Multiwfn ${ito} << EOF > ${ito/.fchk/}_tdm.txt 2>&1
18
1
${ito/.fchk/}.log
1
1
2
exit
EOF
}


# 处理文件
deal_tdm_info() {
	# 输入文件名
	local input_file=$1

	# 提取包含两个字符串之间的内容
	awk '/Calculation took up wall clock time/, /Excitation energy of this state/' "$input_file" > "${input_file/.txt/}_info.txt"

	echo "信息内容已保存到 ${input_file/.txt/}_info.txt"
}

for i in $file_pattern ;do
    deal_fchk $i
    deal_tdm_info ${i/.fchk/}_tdm.txt
    rm ${i/.fchk/}_tdm.txt
done

wait

exit 0

