#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.fchk] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.fchk 文件使用"
    echo ""
    echo "生成分子中每个原子体积，以 Electron density (rho) 函数分割"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.fchk"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_fchk() {
    local ito=$1
    echo "Converting $1"
    Multiwfn ${ito} << EOF > ${i/.fchk/}-atom_space.txt 2>&1
15
1
1
exit
EOF
}


# 处理文件 Area unit is in Angstrom^2


for i in $file_pattern ;do
    deal_fchk $i
    awk '/ Calculation took up/,/ Summing up absolute value/' ${i/.fchk/}-atom_space.txt > ${i/.fchk/}-as1.txt
    mv ${i/.fchk/}-as1.txt ${i/.fchk/}-atom_space.txt 
done

wait

exit 0

