#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.gjf] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.gjf 文件使用"
    echo ""
    echo "生成RedDim=ClearLowFreq=??? 对计算光谱的频率进行筛选)"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.gjf"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_gjf() {
    local ito=$1
    echo "Generate $1"
 
    for i in {1..12}; do
	value=$((800 + (50 * i)))
        filename="${1/.gjf/}_${value}.gjf"
        sed "s/RedDim=ClearLowFreq=[^ ]*/RedDim=ClearLowFreq=${value}/g" $1 > $filename	
        echo "Generated: $filename"
    done
}


# 处理文件


for i in $file_pattern ;do
    deal_gjf $i
done

wait

exit 0

