#!/bin/bash

# 显示帮助信息
show_help() {
    echo "用法 : $(basename "$0") [filename.fchk] "
    echo ""
    echo "若直接使用 $(basename "$0") 则对所有 *.fchk 文件使用"
    echo ""
    echo "生成带有分子体积的 .pdb 文件，可配合 VMD 绘制盒子"
}

# 检查上一个命令的退出状态
check_error() {
    if [[ $? -ne 0 ]]; then
        echo "错误: $1 失败"
    fi
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [ -z "$1" ]; then
  file_pattern="*.fchk"
else
  file_pattern="$1"
fi

# 执行转换和移动的函数
deal_fchk() {
    local ito=$1
    echo "Converting .fchk"
    Multiwfn ${ito} << EOF > /dev/null 2>&1
100
21
size
2
exit
EOF
}


# 处理文件


for i in $file_pattern ;do
    deal_fchk $i
    mv new.pdb ${i/.fchk/}.pdb
done

wait

exit 0

