#!/bin/bash

show_help() {
    echo ""
    echo "常用的 命令"
    echo ""
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
     show_help
     exit 0
fi

echo "批量处理 电子空穴后缀连接符号"
echo "find . -type f -name '*_ele.cub*' -exec bash -c 'mv \"\$1\" \"\${1//_ele.cub/-ele.cub}\"' _ {} \;"
echo "find . -type f -name '*_hole.cub*' -exec bash -c 'mv \"\$1\" \"\${1//_hole.cub/-hole.cub}\"' _ {} \;"
