#!/bin/bash

show_help() {
    echo
    echo "用法: $(basename "$0") [pattern.pdb]"
    echo
    echo "将 aimd 计算得到的 pdb 文件处理为 Python 可处理的 pdb 文件"
    echo "新生成的文件 会带有 _MD 后缀"
}

# 如果传入了 -h 或 --help，显示帮助信息并退出
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi


# 提取文件名（去掉扩展名）和扩展名
filename=$(basename -- "$1")
extension="${filename##*.}"
filename="${filename%.*}"

# 生成新的文件名，添加"_MD"后缀
new_filename="${filename}_MD.${extension}"

# 使用awk处理输入文件并保存到新文件
awk '
{
    # 如果当前行包含"END"并且不包含"ENDMDL"
    if ($0 ~ /END/ && $0 !~ /ENDMDL/) {
        # 将"END"替换为"ENDMDL"
        gsub(/END/, "ENDMDL", $0)
    }

    # 打印当前行
    print $0
    
    # 如果当前行包含"CRYST1"
    if ($0 ~ /CRYST1/) {
        # 在当前行后插入一行"MODEL"
        print "MODEL"
    }
}' "$1" > "$new_filename"  # 处理输入文件($1)并将结果保存到新文件

